### ISSUE TITLE
Не убрала border

### ISSUE THREAD

**Issue by scandy5** [AlenaLoik/Uber#2]
В макете: 
![image](https://user-images.githubusercontent.com/41551315/58157270-9ccf4c00-7c80-11e9-88e2-b82b25269111.png)
У тебя: 
![image](https://user-images.githubusercontent.com/41551315/58157287-a48ef080-7c80-11e9-8a48-c4b2eae63cb6.png)

**Comment by AlenaLoik** [comment]
Зробила border: 0;
