### ISSUE TITLE
Разные расстояния 

### ISSUE THREAD

**Issue by scandy5** [AlenaLoik/Uber#6]
У тебя: 
![image](https://user-images.githubusercontent.com/41551315/58157785-c177f380-7c81-11e9-95e9-556d12a0b5f7.png)
В макете:
![image](https://user-images.githubusercontent.com/41551315/58157803-cb99f200-7c81-11e9-838c-47aaa04e5a95.png)

**Comment by AlenaLoik** [comment]
Виправила .underline{
        margin-bottom: 43px;
}
